import { QA } from "../types";

export const ACADEMIC_KNOWLEDGE: QA[] = [
  // ==================== MAJORS - CS (Computer Science) ====================
  {
    questions: [
      "cs",
      "computer science",
      "cs department",
      "about cs",
      "programming major",
      "programming",
      "what is cs",
      "is cs hard",
      "cs subjects",
      "cs courses",
      "حاسب",
      "علوم حاسب",
      "قسم الحاسب",
      "تخصص برمجة",
      "معلومات عن الحاسب",
      "برمجة",
      "يعني ايه حاسب",
      "صعب ولا سهل",
      "مواد حاسب",
      "ادخل حاسب",
    ],
    answer: {
      ar: [
        "💻 **علوم الحاسب (CS):** التخصص الأقوى حالياً! بتدرس فيه لغات برمجة، خوارزميات، وذكاء اصطناعي. فرص الشغل فيه مالهاش أول من آخر.",
        "🖥️ **Computer Science:** ده المستقبل حرفياً. لو بتحب حل المشاكل (Problem Solving) والكود، ده مكانك. المواد: Java, C++, Networks.",
        "🚀 **تخصص CS:** مش بس كود! ده تفكير منطقي وإبداع. هتعمل برامج، مواقع، وتطبيقات موبايل. نصيحة: طبق بإيدك كتير.",
        "👨‍💻 **قسم الحاسب:** بيخرج مبرمجين ومحللين نظم. الدراسة ممتعة بس محتاجة مجهود ومتابعة للتطورات التكنولوجية.",
        "💡 **عن CS:** تخصص العباقرة! المواد بتبدأ من الأساسيات لحد بناء أنظمة كاملة. الشغل مضمون لو كنت شاطر.",
        "🌐 **علوم الحاسب:** هو لغة العصر. هتفهم ازاي الكمبيوتر بيفكر وازاي تخليه ينفذ أوامرك.",
        "🔥 **CS:** لو عايز تعمل فلوس وتأثير، ده الطريق. مجالاته: Web Dev, Mobile App, AI, Cyber Security.",
        "🎓 **الدراسة في الحاسب:** بتركز على الجانب العملي. الامتحانات محتاجة فهم مش حفظ.",
        "⌨️ **CS Major:** Coding is Art. هتتعلم تكتب كود نضيف وفعال.",
        "🌟 **نصيحة لحاسب:** الانجليزي بتاعك لازم يكون قوي، والـ Self-study هو سر النجاح.",
      ],
      en: [
        "💻 **Computer Science (CS):** The most powerful major today! Covers coding, algorithms, and AI. Endless career opportunities.",
        "🖥️ **Computer Science:** Literally the future. If you love Problem Solving, this is for you. Courses: Java, C++, Networks.",
        "🚀 **CS Major:** Not just code, it's logic & creativity. Build apps, webs, and systems. Tip: Practice makes perfect.",
        "👨‍💻 **CS Dept:** Produces programmers & analysts. Fun study but needs effort and keeping up with tech.",
        "💡 **About CS:** Major for geniuses! Starts from basics to full systems. Jobs are guaranteed if you are skilled.",
        "🌐 **CS:** The language of the era. Understand how computers think.",
        "🔥 **CS:** Want impact & money? This is the way. Fields: Web, Mobile, AI, Security.",
        "🎓 **Studying CS:** Focuses on practicals. Exams need understanding, not memorization.",
        "⌨️ **CS Major:** Coding is Art. Learn to write clean, efficient code.",
        "🌟 **CS Advice:** Strong English is a must. Self-study is the secret.",
      ],
    },
  },

  // ==================== MAJORS - MIS (Management Info Systems) ====================
  {
    questions: [
      "mis",
      "information systems",
      "management information systems",
      "about mis",
      "is mis good",
      "mis subjects",
      "mis jobs",
      "system analysis",
      "نظم",
      "نظم معلومات",
      "قسم النظم",
      "تخصص نظم",
      "معلومات عن نظم",
      "نظم معلومات ادارية",
      "شغل نظم",
      "مواد نظم",
      "يعني ايه نظم",
    ],
    answer: {
      ar: [
        "📊 **نظم المعلومات (MIS):** حلقة الوصل بين التكنولوجيا والبيزنس. بتفهم لغة المبرمجين ولغة المديرين.",
        "📈 **تخصص MIS:** تخصص 'الجوكر'. بتدرس شوية برمجة وداتا بيز، وشوية إدارة ومحاسبة. مجالاتك واسعة جداً.",
        "💼 **قسم نظم:** بيخرج محلل نظم (System Analyst) ومدير مشاريع. التخصص ده مطلوب جداً في الشركات الكبيرة.",
        "🔗 **MIS:** لو بتحب التكنولوجيا بس مش عايز تفضل تكتب كود طول اليوم، ده أنسب مكان ليك.",
        "🗂️ **مواد MIS:** قواعد بيانات (SQL)، تحليل وتصميم نظم، تجارة إلكترونية، ومبادئ إدارة.",
        "🚀 **مستقبل نظم:** ممكن تشتغل Developer، ممكن Tester، وممكن Project Manager. أنت اللي بتحدد طريقك.",
        "💡 **عن النظم:** التخصص اللي بيخليك فاهم 'السيستم' ماشي ازاي من الأول للآخر.",
        "🎓 **الدراسة في نظم:** ميكس مريح بين العملي والنظري. مش صعب زي حاسب ولا نظري زي تجارة.",
        "🌟 **نصيحة لنظم:** ركز على الـ Data Analysis والـ SQL، دول مستقبل التخصص ده.",
        "✨ **MIS:** التكنولوجيا في خدمة الإدارة. ده باختصار.",
      ],
      en: [
        "📊 **MIS:** The bridge between Tech & Business. You speak both programmer & manager languages.",
        "📈 **MIS Major:** The 'Joker' major. Some coding/DB, some management/accounting. Very broad career paths.",
        "💼 **MIS Dept:** Graduates System Analysts & PMs. Highly demanded in big corps.",
        "🔗 **MIS:** Love tech but hate coding 24/7? This is for you.",
        "🗂️ **MIS Subjects:** Databases (SQL), System Analysis, E-Commerce, Management basics.",
        "🚀 **MIS Future:** Be a Developer, Tester, or Project Manager. You choose your path.",
        "💡 **About MIS:** Understanding how the 'System' works end-to-end.",
        "🎓 **Studying MIS:** Balanced mix of practical & theory. Not as hard as CS, not as dry as Business.",
        "🌟 **MIS Advice:** Focus on Data Analysis & SQL, that's the gold mine.",
        "✨ **MIS:** Tech serving Business. Simply put.",
      ],
    },
  },

  // ==================== GRADING & GPA (DETAILED) ====================
  {
    questions: [
      "grading system",
      "grades map",
      "score guide",
      "calculate grade",
      "gpa scale",
      "passing grade",
      "grade distribution",
      "what is a+",
      "what is f",
      "نظام الدرجات",
      "توزيع الدرجات",
      "التقديرات",
      "حساب الدرجة",
      "كم A",
      "درجاتي",
      "النجاح من كام",
      "تقدير الامتياز",
      "درجة الرسوب",
      "توزيعة الدرجات",
    ],
    answer: {
      ar: [
        "📜 **نظام التقديرات:**\nA+ (95-100) | A (90-94)\nB+ (85-89) | B (80-84)\nC+ (75-79) | C (70-74)\nD+ (65-69) | D (60-64)\nF (أقل من 60) ❌",
        "📊 **الدرجات:** عشان تجيب امتياز (A) محتاج فوق 90. الجيد جداً بيبدأ من 80. والنجاح من 60 صافي.",
        "📝 **التقييم:** أعمال سنة + ميدتيرم + فاينل. الفاينل لوحده عليه أكبر درجة (40-50). اهتم بكل جزء.",
        "🏆 **الـ GPA:** بيتحسب بناءً على النقاط. الـ A+ بتديك 4.0 نقاط (كاملة). حاول دايماً تكون فوق الـ 3.0.",
        "⚠️ **تنبيه:** أقل من 60 تعتبر راسب (F) وهتعيد المادة. شد حيلك!",
        "✨ **نصيحة:** الـ D والـ D+ بيقللوا المعدل جداً. حاول دايماً تلعب على الـ B لفوق.",
        "📈 **توزيعة مادة العملي:** 20 الميدتيرم، 40 أعمال سنة (تاسكات وحضور)، 40 فاينل.",
        "📉 **توزيعة النظري:** 20 ميدتيرم، 30 أعمال سنة، 50 فاينل. (بتختلف شوية حسب المادة).",
        "🥇 **الامتياز:** مش مستحيل! احضر المحاضرات، سلم الشيتات، وحل امتحانات سابقة.",
        "🔢 **النقاط:**\nA+ = 4.0\nA = 3.7\nB+ = 3.3\nB = 3.0\nC+ = 2.7\nC = 2.4\nD+ = 2.0\nD = 1.0",
      ],
      en: [
        "📜 **Grading System:**\nA+ (95-100) | A (90-94)\nB+ (85-89) | B (80-84)\nC+ (75-79) | C (70-74)\nD+ (65-69) | D (60-64)\nF (< 60) ❌",
        "📊 **Grades:** Ace (A) starts at 90. Very Good starts at 80. Passing is 60 flat.",
        "📝 **Assessment:** Coursework + Midterm + Final. Finals carry 40-50%. Every mark counts.",
        "🏆 **GPA:** Based on points. A+ gives 4.0 (Full). Aim to stay above 3.0.",
        "⚠️ **Warning:** Below 60 is a Fail (F) -> Retake. Study hard!",
        "✨ **Tip:** D & D+ tank your GPA. Aim for B and above.",
        "📈 **Practical Course:** 20 Mid, 40 Work, 40 Final.",
        "📉 **Theory Course:** 20 Mid, 30 Work, 50 Final. (Varies slightly).",
        "🥇 **Getting A+:** Possible! Attend lectures, submit sheets, solve past papers.",
        "🔢 **Points:**\nA+ = 4.0\nA = 3.7\nB+ = 3.3\nB = 3.0\nC+ = 2.7\nC = 2.4\nD+ = 2.0\nD = 1.0",
      ],
    },
  },

  // ==================== GPA CALCULATION (HOW-TO) ====================
  {
    questions: [
      "gpa calculation",
      "how to calc gpa",
      "semester gpa",
      "cgpa",
      "calculate my gpa",
      "formula for gpa",
      "gpa method",
      "طريقة حساب المعدل",
      "كيف احسب المعدل",
      "المعدل الفصلي",
      "المعدل التراكمي",
      "قانون المعدل",
      "ازاي احسب ال gpa",
      "حسبة الدرجات",
    ],
    answer: {
      ar: [
        "🧮 **معادلة الـ GPA:** (مجموع النقاط × الساعات) ÷ (مجموع الساعات الكلي).",
        "💡 **ببساطة:**\n1. مادة 3 ساعات جبت فيها A (يعني 3.7 نقطة) -> 3 × 3.7 = 11.1\n2. احسب كده لكل المواد واجمع النواتج.\n3. اقسم المجموع على عدد ساعات الترم كله.",
        "📱 **نصيحة:** استخدم حاسبة المعدل في التطبيق أسهل وأدق!",
        "🔢 **مثال سريع:** لو عندك 6 مواد وكلهم 3 ساعات، وجبت فيهم كلهم B (3 نقاط).\nالمعدل = 3.0.",
        "🎓 **التراكمي (CGPA):** هو متوسط معدلاتك في كل الترمات اللي فاتت.",
        "📈 **رفع المعدل:** أسهل طريقة هي إنك تجيب A في المواد اللي ساعاتها كتير (زي 3 أو 4 ساعات).",
        "📉 **نزول المعدل:** الـ F بتدمر المعدل لأنها 0 نقاط بس ساعاتها بتتحسب في المقام. احذر!",
        "🔄 **الإعادة:** لو عدت مادة، الدرجة الجديدة بتتحسب في التراكمي والقديمة بتفضل موجودة بس تأثيرها بيقل.",
        "📝 **ورقة وقلم:** اعمل جدول، حط المواد، الساعات، والدرجة المتوقعة واحسبها.",
        "🤖 **أنا ممكن أساعدك:** قول لي درجاتك وساعات المواد وأنا أحاول أحسبلك (قريباً 😉).",
      ],
      en: [
        "🧮 **GPA Formula:** (Sum of [Points × Hours]) ÷ (Total Hours).",
        "💡 **Simply:**\n1. 3-hour course, grade A (3.7 pts) -> 3 × 3.7 = 11.1\n2. Do this for all, sum them.\n3. Divide by total term hours.",
        "📱 **Tip:** Use the built-in GPA Calculator, it's easier!",
        "🔢 **Quick Ex:** 6 courses, all 3 hours, all B (3.0 pts) -> GPA = 3.0.",
        "🎓 **CGPA:** Average of all your semester GPAs.",
        "📈 **Boosting GPA:** Get A's in high-credit courses (3 or 4 hours).",
        "📉 **Dropping GPA:** F is 0 points but hours count. It hurts bad. Avoid it!",
        "🔄 **Retake:** New grade counts in CGPA, old one stays on transcript but impact lessens.",
        "📝 **Manual:** Make a table: Course | Hours | Expected Grade. Calc it.",
        "🤖 **I can help:** (Soon) I'll be able to calc it for you interactively.",
      ],
    },
  },

  // ==================== EXAMS ADVICE ====================
  {
    questions: [
      "midterm",
      "midterm exam",
      "midterm advice",
      "midterm weight",
      "finals",
      "final exam",
      "exam tips",
      "how to study",
      "ميدتيرم",
      "نصفي",
      "اختبار نصفي",
      "نصائح للميدتيرم",
      "درجة الميدتيرم",
      "فاينل",
      "النهائي",
      "ازاي اذاكر",
      "نصائح للامتحان",
    ],
    answer: {
      ar: [
        "📝 **الميدتيرم:** دا فرصتك تلم درجات! غالباً بييجي من الشيتات والمحاضرات بالنص. ذاكر الشيتات كويس.",
        "🎓 **الفاينل:** بيحتاج نفس طويل. قسم المنهج، ولازم تحل امتحانات سنين فاتت (Previous Exams) لأن الأفكار بتتكرر.",
        "💡 **نصيحة ذهبية:** الدكتور غالباً بيقول في المحاضرة 'دي مهمة' أو 'دي جاية في الامتحان'. ركز في الحاجات دي.",
        "🚫 **تجنب:** السهر ليلة الامتحان. قلة النوم بتخليك تنسى وتغلط في الجمع والطرح البسيط.",
        "📚 **مصادر:** التزم بكتاب المعهد واستايلات المحاضرة. مصادر خارجية ممكن تشتتك إلا لو مش فاهم نقطة معينة.",
        "⚡ **ليلة الامتحان:** مراجعة سريعة على العناوين والقوانين. بلاش تذاكر جديد.",
        "🤝 **Group Study:** المذاكرة الجماعية مفيدة للمراجعة وحل المسائل، بس بلاش تتحول لقعدة صفا! 😂",
        "🖊️ **في اللجنة:** اقرأ الورقة كلها الأول. ابدأ بالسهل والمضمون عشان تكتسب ثقة.",
        "📅 **الجدول:** نزل جدول الامتحانات بدري واعرف أماكن اللجان عشان متبقاش متوتر يومها.",
        "🧠 **التركيز:** افصل موبايلك وانت بتذاكر. نوتيفيكيشن واحدة كفيلة تضيع ساعة.",
      ],
      en: [
        "📝 **Midterms:** Your chance to bag marks! Usually directly from Sheets/Lectures. Study Sheets well.",
        "🎓 **Finals:** Needs endurance. Split syllabus, solve Previous Exams (Patterns repeat!).",
        "💡 **Golden Tip:** Prossors say 'This is important' in lectures. Mark those, they ARE comping.",
        "🚫 **Avoid:** All-nighters. Lack of sleep = stupid mistakes.",
        "📚 **Sources:** Stick to slides & book. External sources confuse you unless strictly needed.",
        "⚡ **Exam Eve:** Quick review of headers/formulas. Don't start new topics.",
        "🤝 **Group Study:** Good for revision, bad if it turns into a party! 😂",
        "🖊️ **In Exam:** Read full paper. Start with easy Qs to gain confidence.",
        "📅 **Schedule:** Check timetable & venue early to reduce stress.",
        "🧠 **Focus:** DND mode on phone. One notification = One hour lost.",
      ],
    },
  },
];
