import { QA } from "../types";

export const FAQ_KNOWLEDGE: QA[] = [
  // ==================== LOCATION & TRANSPORT ====================
  {
    questions: [
      "location",
      "address",
      "where is institute",
      "map",
      "google maps",
      "how to go",
      "transportation",
      "bus",
      "microbus",
      "metro",
      "routes",
      "الموقع",
      "العنوان",
      "فين المعهد",
      "مكان المعهد",
      "مواصلات",
      "الباص",
      "اركب ايه",
      "ازاي اروح",
      "عنوان المعهد",
      "خريطة",
      "اقرب محطة",
      "طريق المعهد",
    ],
    answer: {
      ar: [
        "📍 **العنوان:** مدينة العبور - الحي السابع - أمام كارفور العبور مباشرة.",
        "🚌 **موقف العاشر:** اركب أي عربية رايحة 'عبور' وانزل الحي السابع (قدام المعهد).",
        "🚇 **من المترو:** انزل 'عدلي منصور' (الخط الثالث) واركب ميكروباص للحي السابع.",
        "🚗 **بالعربية:** طريق الإسماعيلية الصحراوي -> مدخل العبور -> كمل للحي السابع.",
        "🗺️ **Google Maps:** ابحث عن 'Obour High Institute for Management & Informatics'.",
        "🚍 **من رمسيس:** موقف أحمد حلمي أو القللي -> ميكروباصات العبور.",
        "🚌 **من المؤسسة:** اركب عبور وانزل قدام كارفور.",
        "🏢 **المبنى:** تلاقينا المبنى الكبير اللي مكتوب عليه 'معاهد العبور'.",
        "🚶 **مشياً:** لو ساكن في العبور، إحنا في قلب الحي السابع جنب مجمع المدارس.",
        "🚕 **Uber:** اطلب 'معاهد العبور' وهيوصلك للبوابة.",
      ],
      en: [
        "📍 **Address:** Obour City, 7th District, Opposite Carrefour Obour.",
        "🚌 **From Salam (Al-Asher):** Take 'Obour' microbus, get off at 7th District.",
        "🚇 **Metro:** Adly Mansour Stn (Line 3) -> Microbus to 7th District.",
        "🚗 **Car:** Ismailia Desert Rd -> Obour Entrance -> 7th District.",
        "🗺️ **Maps:** Search 'Obour High Institute'.",
        "🚍 **From Ramses:** Ahmed Helmy Station -> Obour Vans.",
        "🚌 **From shoubra:** Take Obour bus -> Get off at Carrefour.",
        "🏢 **Building:** The huge building marked 'Obour Institutes'.",
        "🚶 **Local:** Heart of 7th District, near Schools Complex.",
        "🚕 **Uber:** Destination 'Obour Institutes' takes you to gate.",
      ],
    },
  },

  // ==================== FEES & MONEY ====================
  {
    questions: [
      "fees",
      "payment",
      "tuition",
      "cost",
      "money",
      "price",
      "expenses",
      "how much",
      "installments",
      "bank",
      "مصاريف",
      "دفع",
      "فلوس",
      "تكلفة",
      "رسوم",
      "المصاريف كام",
      "الاقساط",
      "البنك",
      "طريقة الدفع",
      "اسعار",
      "مصاريف السنة",
    ],
    answer: {
      ar: [
        "💰 **المصاريف:** بتختلف كل سنة. لازم ترجع لشؤون الطلاب (في المعهد) عشان الرقم الأكيد.",
        "🏦 **الدفع:** عن طريق (فيزا المعهد) أو إيداع بنكي في CIB / البنك الأهلي.",
        "💳 **أونلاين:** حالياً مفيش دفع أونلاين مباشر من الموقع، لازم البنك.",
        "📅 **الأقساط:** غالباً المصاريف بتتقسم على قسطين (واحد الترم الأول وواحد التاني).",
        "💸 **الكتب:** مصاريف الكتب بتكون جزء من المصاريف الإجمالية، بس اتأكد من الشؤون.",
        "🛑 **غرامات:** التأخير في الدفع عليه غرامات. حاول تدفع في المواعيد المحددة.",
        "🧾 **إيصال:** احتفظ بأصل إيصال الدفع! ده إثباتك الوحيد.",
        "📞 **استفسار:** اتصل برقم المعهد الأرضي لمعرفة أحدث أرقام المصروفات.",
        "💵 **زيادة سنوية:** المصاريف بتزيد كل سنة بنسبة بسيطة (وزارة التعليم بتحددها).",
        "🤝 **منح:** المتفوقين (أوائل الدفعة) ليهم خصومات كبيرة!",
      ],
      en: [
        "💰 **Fees:** Amounts vary yearly. Check Student Affairs physically for exact figures.",
        "🏦 **Payment:** Via CIB Institute Card OR Bank Deposit (NBE/CIB).",
        "💳 **Online:** No direct site pay yet. Bank only.",
        "📅 **Installments:** Usually split in 2 (Term 1 & Term 2).",
        "💸 **Books:** Book fees are usually bundled, but confirm with admin.",
        "🛑 **Fines:** Late payment = Fine. Pay on time.",
        "🧾 **Receipt:** Keep your original receipt! It's your proof.",
        "📞 **Call:** Call landline for latest fee structure info.",
        "💵 **Yearly Hike:** Small % increase yearly (Ministry regulated).",
        "🤝 **Scholarships:** Top rankers get huge discounts!",
      ],
    },
  },

  // ==================== STUDENT AFFAIRS (OFFICE) ====================
  {
    questions: [
      "student affairs",
      "affairs office",
      "contact admin",
      "office hours",
      "registrar",
      "papers",
      "submission",
      "شؤون الطلاب",
      "مكتب الشؤون",
      "التسجيل",
      "مواعيد العمل",
      "الادارة",
      "اقدم ورق",
      "ساعات العمل",
      "مكان الشؤون",
    ],
    answer: {
      ar: [
        "🏢 **المكان:** المبنى الإداري - الدور الأرضي (على اليمين وانت داخل).",
        "⏰ **المواعيد:** يومياً من 9 صباحاً لـ 2 ظهراً (ما عدا الجمعة والسبت).",
        "📞 **تواصل:** يفضل تروح بنفسك لأن التليفونات دايماً مشغولة.",
        "📄 **الأوراق:** شهادة الثانوية (أصل) + شهادة ميلاد (أصل) + 6 صور + نموذج 2 جند (للذكور).",
        "🆔 **الكارنيه:** استلام الكارنيه من الشؤون بعد دفع القسط الأول.",
        "📝 **إثبات قيد:** لو محتاجه عشان الجيش أو مواصلات، اطلبه من الشؤون (بيطلع في يومين).",
        "🗂️ **الملف:** ملفك الشخصي مسؤوليتهم. لو سحبت ملفك بتدفع رسوم سحب.",
        "👔 **التعامل:** الموظفين هناك لخدمتك، بس خليك صبور لأن الضغط كبير.",
        "🚪 **الدخول:** لازم يكون معاك إثبات شخصية وأنت داخل من البوابة.",
        "📋 **اللوحات:** بص دايماً على لوحة الإعلانات برة الشؤون، بينزل عليها قرارات مهمة.",
      ],
      en: [
        "🏢 **Location:** Admin Building - Ground Floor (Right side).",
        "⏰ **Hours:** 9 AM - 2 PM daily (Closed Fri/Sat).",
        "📞 **Contact:** Better go in person. Phones are always busy.",
        "📄 **Docs:** High School Cert (Original) + Birth Cert + 6 Photos + Military form (Males).",
        "🆔 **ID Card:** Pickup from Affairs after paying 1st installment.",
        "📝 **Enrollment Cert:** Need it for Army/Travel? Request there (Takes 2 days).",
        "🗂️ **File:** Your academic file lives there. Withdraw fees apply.",
        "👔 **Staff:** There to help, but busy. Be patient.",
        "🚪 **Gate:** Need National ID to enter campus if you don't have Uni ID.",
        "📋 **Notice Board:** Check the board outside office for official news.",
      ],
    },
  },
];
