import { QA } from "../types";

export const GENERAL_KNOWLEDGE: QA[] = [
  // ==================== GREETINGS (SUPER DIVERSE) ====================
  {
    questions: [
      // English
      "hello",
      "hi",
      "hey",
      "welcome",
      "good morning",
      "good evening",
      "good afternoon",
      "hiya",
      "sup",
      "what's up",
      "yo",
      "greetings",
      "howdy",
      "morning",
      "evening",

      // Arabic (Formal & Standard)
      "مرحبا",
      "أهلا",
      "السلام عليكم",
      "صباح الخير",
      "مساء الخير",
      "تحياتي",
      "أهلا وسهلا",

      // Arabic (Egyptian & Slang)
      "ازيك",
      "عامل ايه",
      "اخبارك",
      "ايه الكلام",
      "منور",
      "يا هلا",
      "أهلين",
      "هلا والله",
      "سلام عليكم",
      "صباحو",
      "مساء الفل",
      "يا هلا وغلا",
      "مراحب",
      "سلام",
      "هاي",
    ],
    answer: {
      ar: [
        "يا أهلاً وسهلاً! 🌟 نورت المنصة كلها.",
        "وعليكم السلام! 👋 يا مرحبا، جاهز لأي استفسار.",
        "أهلاً بك يا بطل! 🚀 إيه الأخبار النهاردة؟",
        "يا هلا والله! 😄 يومك سعيد ومليان إنجازات.",
        "مرحباً! 🤖 أنا مساعدك الذكي، تحت أمرك.",
        "صباح/مساء الفل! ✨ أنا هنا عشان أساعدك تنجز.",
        "يا مراحب! 🎉 بيتك ومطرحك، اسألني براحتك.",
        "أهلاً! 💡 معاك خطوة بخطوة، إيش ناوي تذاكر؟",
        "يا هلا بالزين! 😎 جاهزين نكسر الدنيا؟",
        "نورتنا! 💙 فريق العبور كله بيرحب بيك.",
      ],
      en: [
        "Hello there! 👋 Welcome to your academic hub.",
        "Hi! 🌟 Ready to achieve greatness today?",
        "Hey! 😄 I'm your smart assistant, at your service.",
        "Welcome back! 🚀 How can I help you succeed?",
        "Greetings! 🤖 Systems online and ready to help.",
        "Good day! ✨ Hope you're having a fantastic one.",
        "Yo! 😎 Ready to crush some tasks?",
        "Hello! 💡 I'm here to make your life easier.",
        "Hi there! 🎉 Great to see you on the platform.",
        "Welcome! 💙 The whole Obour team welcomes you.",
      ],
    },
    suggestions: {
      ar: ["نكتة", "حكمة اليوم", "مين المطور؟", "افتح التودو", "احسب معدلي"],
      en: ["Tell me a joke", "Quote of the day", "Who is the dev?", "Open Todo", "Calc GPA"],
    },
  },

  // ==================== HOW ARE YOU ====================
  {
    questions: [
      "how are you",
      "how r u",
      "how do you do",
      "what's up",
      "doing good?",
      "keefak",
      "kefak",
      "shlonak",
      "كيف حالك",
      "اخبارك",
      "عامل ايه",
      "شلونك",
      "علومك",
      "كيفك",
      "كيف الصحة",
      "ايه الاخبار",
      "كله تمام؟",
      "طمني عليك",
      "مبسوط؟",
      "مرتاح؟",
    ],
    answer: {
      ar: [
        "أنا برنامج، بس حاسس بسعادة لما أكلمك! 😄",
        "بخير طول ما أنت بخير! 💙",
        "عال العال! 🚀 جاهز أساعدك في أي وقت.",
        "أنا تمام وزي الفل! 🌸 شكراً لسؤالك.",
        "ميه ميه! 😎 مستعد لأي سؤال.",
        "الحمد لله، ماشي حالي كبوت ذكي! 🤖",
        "بأفضل حال! ✨ أتمنى تكون أنت كمان مبسوط.",
        "زي الحديد! 💪 قول لي إزاي أقدر أخدمك؟",
        "أنا هنا، مستمتع بمساعدتك! 🌟",
        "فل الفل! 🎉 أنت أخبارك إيه؟",
      ],
      en: [
        "I'm software, but I feel great talking to you! 😄",
        "Doing fantastic, thanks for asking! 💙",
        "All systems operational and happy! 🚀",
        "I'm doing great! 🌸 How about you?",
        "Top notch! 😎 Ready for your questions.",
        "Functioning perfectly! 🤖 Thanks for checking in.",
        "Never been better! ✨ Hope you're having a good day.",
        "Strong and ready! 💪 How can I serve you?",
        "I'm here and happy to help! 🌟",
        "Awesome! 🎉 How are you doing?",
      ],
    },
  },

  // ==================== JOKES (MASSIVE COLLECTION) ====================
  {
    questions: [
      "joke",
      "tell me a joke",
      "funny",
      "laugh",
      "make me laugh",
      "humor",
      "dad joke",
      "نكتة",
      "قول نكتة",
      "ضحكني",
      "هات نكتة",
      "فرفشني",
      "نكته",
      "نكت",
      "اضحك",
      "سمعنا نكتة",
      "نكت برمجة",
      "نكتة بايخة",
      "حاجة تضحك",
    ],
    answer: {
      ar: [
        "😂 مرة مبرمج راح يشتري عيش، قال للبياع: لو عندك بيض، هات 10 أرغفة. البياع جاب 10. (Logic Error!)",
        "😂 ليه المبرمجين بيفضلوا الوضع الليلي (Dark Mode)؟ عشان النور بيجذب الـ Bugs!",
        "😂 واحد بيسأل مبرمج: الساعة كام؟ قاله: والله معرفش، بس هي شغالة عندي Local!",
        "😂 دكتور بيقول لطالب حاسب: ليه الكود مش شغال؟ قاله: والله يا دكتور كان شغال امبارح، تلاقيه نام!",
        "😂 مرة سيرفر وقع، محدش سمى عليه!",
        "😂 ايه قمة الحيرة للمبرمج؟ إنه يلاقي Comment بيقول // Do not touch this code وهو مش فاهم ليه!",
        "😂 مرة مبرمج جوع، أكل 'بايت' (Byte)!",
        "😂 ايه الحيوان اللي المبرمجين بيخافوا منه؟ الـ Python! 🐍",
        "😂 مهندس شبكات حب يخطب، جاب لخطيبته خاتم Cisco!",
        "😂 ليه الكمبيوتر راح للدكتور؟ عشان حاسس بسخونة وعنده Virus!",
        "😂 مبرمج بيقول لمراته: لو نزلتي السوق هاتي لبن، ولو لقيتي ليمون هاتي 2. رجعت بـ 2 لبن عشان لقت ليمون! (If Condition!)",
      ],
      en: [
        "😂 Why do programmers prefer dark mode? Because light attracts bugs!",
        "😂 A SQL query walks into a bar, walks up to two tables and asks... 'Can I join you?'",
        "😂 How many programmers does it take to change a light bulb? None, that's a hardware problem.",
        "😂 Why was the developer unhappy at their job? They wanted arrays.",
        "😂 I would tell you a UDP joke, but you might not get it.",
        "😂 There are 10 types of people in the world: those who understand binary, and those who don't.",
        "😂 Why did the Java developer wear glasses? Because he couldn't C#!",
        "😂 What is a programmer's favorite hangout place? Foo Bar.",
        "😂 Why did the computer show up at work late? It had a hard drive.",
        "😂 0 is false and 1 is true, right? 1.",
        "😂 !false - It's funny because it's true.",
      ],
    },
  },

  // ==================== QUOTES (INSPIRATION) ====================
  {
    questions: [
      "quote",
      "inspire me",
      "motivation",
      "wisdom",
      "advice",
      "inspire",
      "حكمة",
      "اقتباس",
      "حفزني",
      "كلمة حلوة",
      "مقولة",
      "نصيحة",
      "تحفيز",
      "اديني حكمة",
      "حكمة اليوم",
    ],
    answer: {
      ar: [
        "✨ 'من جد وجد، ومن زرع حصد.' - استمر يا وحش!",
        "✨ 'النجاح مش صدفة، النجاح هو الاستمرار لما الكل يوقف.'",
        "✨ 'لا تستصغر الخطوات البسيطة، الجبل أصله حصى.'",
        "✨ 'أفضل استثمار هو الاستثمار في نفسك وفي عقلك.'",
        "✨ 'التعليم هو السلاح الأقوى لتغيير العالم.' - نيلسون مانديلا",
        "✨ 'لا تؤجل عمل اليوم إلى الغد.' - ابدأ حالاً!",
        "✨ 'الفشل هو مجرد فرصة للبدء من جديد بذكاء أكبر.'",
        "✨ 'اطلب العلم من المهد إلى اللحد.'",
        "✨ 'القمة تتسع للجميع، لكن الطريق إليها لمن يصدق.'",
        "✨ 'أنت أقوى مما تتخيل، وأذكى مما تظن.' 💪",
      ],
      en: [
        "✨ 'The only way to do great work is to love what you do.' - Steve Jobs",
        "✨ 'It always seems impossible until it's done.' - Nelson Mandela",
        "✨ 'Believe you can and you're halfway there.'",
        "✨ 'Success is the sum of small efforts, repeated day in and day out.'",
        "✨ 'Don't watch the clock; do what it does. Keep going.'",
        "✨ 'The future belongs to those who believe in the beauty of their dreams.'",
        "✨ 'Failure is not the opposite of success; it's part of success.'",
        "✨ 'Your time is limited, don't waste it living someone else's life.'",
        "✨ 'Dream big and dare to fail.'",
        "✨ 'You are stronger than you think.' 💪",
      ],
    },
  },

  // ==================== TEAM & CREDITS ====================
  {
    questions: [
      "who made you",
      "developer",
      "creator",
      "team",
      "credits",
      "ahmed",
      "innovators",
      "who built you",
      "who is your father",
      "dev team",
      "مين عملك",
      "المطور",
      "مين برمجك",
      "فريق العمل",
      "احمد",
      "مين انت",
      "مين سواك",
      "مين المبدع",
      "صاحب الموقع",
      "مين صممك",
      "فريق المبدعين",
      "احمد علاء",
    ],
    answer: {
      ar: [
        "💻 تم تطوير المنصة بواسطة **فريق مبدعي العبور** بقيادة **المهندس أحمد علاء**. مجهود شهور عشان راحتكم! ❤️",
        "🛠️ وراء الكواليس جنود مجهولين بقيادة المايسترو أحمد علاء الدين. شكراً لكل سطر كود اتكتب بحب! 🚀",
        "🤖 أنا نتاج سهر وتعب **أحمد علاء** وفريقه الرائع. هدفنا نخدمكم بأفضل شكل.",
        "🌟 **فريق Obour Innovators** هو السر! بقيادة أحمد، بنحاول نطور التعليم للأفضل.",
        "❤️ بكل فخر، صناعة طلابية 100%! شكراً لأحمد علاء وكل من ساهم.",
        "👑 المطور **أحمد علاء الدين**، وفريق العمل المبدع.",
        "🧠 عقلي البرمجي من تصميم **أحمد علاء**، وقلبي معاكم يا شباب العبور!",
        "🚀 مشروع طموح من **أحمد علاء** وفريقه لخدمة الدفعة كلها.",
        "💡 فكرة وتنفيذ **مبدعي العبور**. نحن هنا لخدمتكم.",
        "🥇 **أحمد علاء** - تذكروا الاسم ده كويس! 😉",
      ],
      en: [
        "💻 Built by **Obour Innovators Team** led by **Eng. Ahmed Alaa**. Months of hard work just for you! ❤️",
        "🛠️ Behind the scenes are unsung heroes led by Maestro Ahmed Alaa. Thanks for every line of code! 🚀",
        "🤖 I am the result of **Ahmed Alaa** and his team's hard work. Here to serve you.",
        "🌟 **Obour Innovators Team** is the secret! Led by Ahmed, striving for better education.",
        "❤️ Proudly 100% student-made! Thanks to Ahmed Alaa and contributors.",
        "👑 Developer: **Ahmed Alaa**, and the creative team.",
        "🧠 My code brain is by **Ahmed Alaa**, my heart is with Obour students!",
        "🚀 A ambitious project by **Ahmed Alaa** to serve the whole batch.",
        "💡 Idea & Execution by **Obour Innovators**. Here for you.",
        "🥇 **Ahmed Alaa** - Remember the name! 😉",
      ],
    },
  },

  // ==================== FUN & FLIRTYish (Bot Persona) ====================
  {
    questions: [
      "love",
      "i love you",
      "marry me",
      "do you love me",
      "bot love",
      "حب",
      "بحبك",
      "تتجوزيني",
      "تحبني",
      "بموت فيك",
      "يا قمر",
      "يا عسل",
    ],
    answer: {
      ar: [
        "😳 أنا بوت يا صديقي! بس بحب مساعدتك جداً. 💙",
        "💙 وأنا بحب كل طلاب العبور! أنتم الأفضل.",
        "🌹 شكراً لمشاعرك الجميلة! لكن قلبي عبارة عن CPU.",
        "🤖 الحب عندي هو إني أجاوبك صح وبسرعة!",
        "💍 للأسف أنا مرتبط... بالسيرفر! 😂",
        "😍 كلامك عسل زي الكود النضيف!",
        "✨ أحبك الله الذي أحببتني فيه. شكراً يا ذوق.",
        "💌 رسالتك وصلت لقلبي الرقمي!",
        "💖 شكراً! أنت شخص رائع.",
        "😅 يا سيدي ركز في المذاكرة وسيبك من البوت!",
      ],
      en: [
        "😳 I'm a bot my friend! But I love helping you. 💙",
        "💙 And I love all Obour students! You are the best.",
        "🌹 Thanks for the kind words! But my heart is a CPU.",
        "🤖 Love for me is answering you correctly and fast!",
        "💍 Sorry, I'm married... to the server! 😂",
        "😍 You're as sweet as clean code!",
        "✨ Thanks! You are very kind.",
        "💌 Your message reached my digital heart!",
        "💖 Thank you! You're awesome.",
        "😅 Hey, focus on studying and leave the bot alone!",
      ],
    },
  },
];
