import { QA } from "../types";

export const TECHNICAL_KNOWLEDGE: QA[] = [
  // ==================== LOGIN ISSUES (Troubleshooting) ====================
  {
    questions: [
      "login error",
      "cant login",
      "google sign in error",
      "auth failed",
      "403",
      "access denied",
      "why cant i login",
      "signin not working",
      "account issues",
      "stuck on login",
      "مشكلة دخول",
      "مش عارف ادخل",
      "خطأ تسجيل",
      "جوجل مش شغال",
      "مشكلة في الحساب",
      "مرفوض",
      "مش راضي يحمل",
      "مشكلة تسجيل",
      "الايميل مش بيفتح",
      "عطل تسجيل دخول",
    ],
    answer: {
      ar: [
        "🚫 **مشكلة تسجيل الدخول؟** غالباً حلها بسيط: امسح الـ Cache وجرب تاني.",
        "🔐 **خطأ في الدخول:** تأكد إنك بتستخدم إيميل جوجل (Gmail) مش ياهو أو هوتميل.",
        "🌐 **فحص الشبكة:** أحياناً النت الضعيف بيقطع الاتصال بسيرفر جوجل. جرب شبكة تانية.",
        "🕵️ **Incognito:** جرب تفتح من 'المتصفح الخفي'. لو دخل معاك، يبقى المشكلة في إضافات المتصفح (Extensions).",
        "📧 **تفعيل الحساب:** لو إيميل المعهد، تأكد من شؤون الطلاب إنه مفعل ومش موقوف.",
        "🔧 **صيانة:** لو المشكلة عامة عند الكل، يبقى بنعمل تحديث للسيرفرات. اصبر علينا شوية! ☕",
        "📱 **من الموبايل:** جرب تفتح من الكمبيوتر أو العكس. أحياناً المشكلة في الجهاز نفسه.",
        "🧹 **مسح البيانات:** ادخل إعدادات المتصفح -> Privacy -> Clear Browsing Data.",
        "🆘 **الدعم الفني:** لو جربت كل ده ولسه بايظة، صور الشاشة وابعتها للدعم المباشر.",
        "🔄 **Refresh:** صدق أو لا تصدق، أحياناً F5 بتحل المشكلة! 😂",
      ],
      en: [
        "🚫 **Login Issue?** Usually simple: Clear Cache & Retry.",
        "🔐 **Auth Error:** Ensure using Google Email (Gmail), not Yahoo/Hotmail.",
        "🌐 **Net Check:** Weird connection drops Google Auth. Try proper WiFi/4G.",
        "🕵️ **Incognito:** Try 'Private Mode'. If it works, your Extensions are the culprit.",
        "📧 **Account Active?** If Uni email, confirm with Student Affairs it's not suspended.",
        "🔧 **Maintenance:** If no one can login, we are updating servers. Grab a coffee! ☕",
        "📱 **Cross-Device:** Try PC vs Mobile. Sometimes it's just your device acting up.",
        "🧹 **Clear Data:** Browser Settings -> Privacy -> Clear Browsing Data.",
        "🆘 **Support:** Tried all? Screenshot error & send to Live Support.",
        "🔄 **Refresh:** Believe it or not, F5 works wonders! 😂",
      ],
    },
  },

  // ==================== APP INSTALL (PWA) ====================
  {
    questions: [
      "install app",
      "download apk",
      "ios app",
      "iphone app",
      "android app",
      "pwa",
      "mobile app",
      "get app",
      "where to download",
      "app store link",
      "play store link",
      "تطبيق الايفون",
      "تطبيق الاندرويد",
      "تحميل البرنامج",
      "تثبيت التطبيق",
      "رابط التطبيق",
      "ازاي انزل التطبيق",
      "فين التطبيق",
      "لينك التحميل",
      "اب ستور",
    ],
    answer: {
      ar: [
        "📱 **تطبيقنا (PWA):** مش محتاج ستور! من المتصفح اضغط 'Add to Home Screen'.",
        "🍎 **للآيفون (iOS):** افتح Safari ⬅️ اضغط زر المشاركة (سهم طالع) ⬅️ اختار 'Add to Home Screen'.",
        "🤖 **للأندرويد:** افتح Chrome ⬅️ الثلاث نقط فوق ⬅️ 'Install App'.",
        "⚡ **ليه PWA؟** عشان مياخدش مساحة، وبيحدث نفسه أوتوماتيك، وبيشتغل أوفلاين جزئياً.",
        "🚫 **مش لاقيه على الستور؟** إحنا قاصدين! التكنولوجيا دي أحدث وأسرع ليك.",
        "📲 **شكل التطبيق:** هيظهر أيقونة التطبيق وسط برامجك عادي جداً كأنه Native App.",
        "💾 **المساحة:** حجمه لا يتعدى 2 ميجا! (أخف 100 مرة من تطبيقات الفيسبوك وغيره).",
        "🔄 **التحديث:** أول ما نرفع ميزة جديدة، هتظهرلك فوراً بدون ما تنزل تحديث.",
        "🔔 **الإشعارات:** وافق على الإشعارات عشان يوصلك تنبيهات المحاضرات والمهام.",
        "📦 **APK:** مفيش APK. ده Web App متطور.",
      ],
      en: [
        "📱 **Our App (PWA):** No Store needed! Browser -> 'Add to Home Screen'.",
        "🍎 **iOS (iPhone):** Open Safari ⬅️ Share Button ⬅️ 'Add to Home Screen'.",
        "🤖 **Android:** Open Chrome ⬅️ 3 Dots top-right ⬅️ 'Install App'.",
        "⚡ **Why PWA?** Zero storage used, auto-updates, partial offline mode.",
        "🚫 **Not on Store?** By design! PWA is faster & modern.",
        "📲 **Look & Feel:** Icon appears on home screen just like native apps.",
        "💾 **Size:** < 2MB! (100x lighter than Facebook etc).",
        "🔄 **Updates:** Instant. No need to 'Download Update'.",
        "🔔 **Notifs:** Allow notifications to get Lecture/Task alerts.",
        "📦 **APK:** No APK. It's a Progressive Web App.",
      ],
    },
  },

  // ==================== BUGS & PERFORMANCE ====================
  {
    questions: [
      "slow",
      "lagging",
      "very slow",
      "latency",
      "loading stuck",
      "glitch",
      "bug",
      "crash",
      "stopped working",
      "frozen",
      "بطيء",
      "النت بطيء",
      "الموقع تقيل",
      "بيحمل كتير",
      "معلق",
      "بيعلق",
      "سيرفر واقع",
      "مش شغال",
      "واقف",
      "مهنج",
    ],
    answer: {
      ar: [
        "🐢 **بطيء؟** غالباً النت. جرب Speedtest وشوف السرعة.",
        "🕸️ **تهنيج:** لو الصفحة تقيلة، اقفل التابات التانية وحرر الرامات.",
        "📱 **جهاز قديم؟** المنصة خفيفة، بس الأجهزة القديمة جداً ممكن تعاني مع الجرافيك العالي.",
        "🧹 **الكاش:** تراكم الملفات المؤقتة بيبطئ المتصفح. امسحه هتحس بفرق.",
        "🔄 **تعليق:** لو معلق على شاشه بيضاء، دوس `Ctrl + F5` (Hard Reload).",
        "🚧 **ضغط:** أوقات تسجيل المواد، السيرفر بيكون عليه ضغط رهيب. حاول في وقت هادي.",
        "🐛 **Bug Report:** لو لقيت خطأ برمجي واضح، صور وابعتلنا فوراً.",
        "🌐 **Browser:** بننصح بـ Chrome أو Edge لأفضل أداء. Safari و Firefox شغالين بس Chrome أسرع.",
        "🔋 **Battery:** لو على لابتوب، وصل الشاحن عشان الأداء يكون Max Performance.",
        "👋 **بيفصل:** لو بيعمل Logout لوحده، ده أمان (Session Timeout). ادخل تاني.",
      ],
      en: [
        "🐢 **Slow?** Usually Net. Run Speedtest.",
        "🕸️ **Lag?** Close other tabs to free up RAM.",
        "📱 **Old Device?** We optimize heavily, but very old devices might struggle with glass effects.",
        "🧹 **Cache:** Junk build-up slows browsers. Clear it.",
        "🔄 **Stuck?** White screen -> `Ctrl + F5` (Hard Reload).",
        "🚧 **Load:** Registration week = Server traffic jam. Try off-peak times.",
        "🐛 **Bug:** Found a glitch? Screenshot & Report. We love fixing bugs.",
        "🌐 **Browser:** Chrome/Edge recommended. Best performance engine.",
        "🔋 **Power:** Laptop? Plug in for Max Performance mode.",
        "👋 **Logging out?** Security Session Timeout. Just login again.",
      ],
    },
  },

  // ==================== FILE ISSUES ====================
  {
    questions: [
      "upload fail",
      "download fail",
      "file error",
      "pdf error",
      "corrupt",
      "cant open file",
      "limit exceeded",
      "فشل الرفع",
      "مش بيحمل",
      "الملف بايظ",
      "مش راضي يفتح",
      "حجم الملف",
    ],
    answer: {
      ar: [
        "📤 **فشل الرفع:** ملفك أكبر من 10 ميجا؟ صغر حجمه (Compress PDF).",
        "📂 **صيغة الملف:** بنقبل PDF, Images, Office Docs. ملفات .exe أو .zip ممنوعة.",
        "📥 **فشل التحميل:** متصفحك ممكن يكون حاجب الـ Pop-ups. اسمح بيها للموقع.",
        "🛡️ **Antivirus:** أحياناً برامج الحماية بتفتكر الملفات فيروسات غلط. افحصه وتأكد.",
        "📄 **PDF فاضي:** لو فتحته لقيته ابيض، النت قطع أثناء التحميل. حمله تاني.",
        "🛑 **ممنوع الرفع:** لو ميعاد التسليم فات (Due Date)، زرار الرفع بيختفي.",
        "🔗 **رابط مكسور:** لو ضغطت وملف مفتحش، بلغ الدعم باسم المادة والمحاضرة.",
        "📱 **موبايل:** الرفع من الموبايل (iPhone بالذات) رخم شوية. جرب PC أسهل.",
        "🕒 **وقت طويل:** لو بياخد وقت طويل بيعمل Timeout. اختار شبكة واي فاي سريعة.",
        "💾 **Corrupt:** الملف تالف؟ جرب تنزله بمتصفح تاني.",
      ],
      en: [
        "📤 **Upload Fail:** >10MB? Compress your PDF online.",
        "📂 **Format:** PDF/Images/Docs only. No .exe or .zip allowed.",
        "📥 **Download Fail:** Browser blocking Pop-ups? Allow them.",
        "🛡️ **Antivirus:** False positives happen. Check your AV content filter.",
        "📄 **Blank PDF:** Download interrupted. Redownload.",
        "🛑 **Cant Upload:** Passed Deadline? Upload button vanishes.",
        "🔗 **Broken Link:** File 404? Tell support Subject+Lecture name.",
        "📱 **Mobile:** Uploading from iOS filesystem is tricky. PC is smoother.",
        "🕒 **Timeout:** Taking too long? Switch to faster WiFi.",
        "💾 **Corrupt:** File won't open? Try different browser.",
      ],
    },
  },
];
